/**
 * ProcessMaker API
 * An API to access ProcessMaker core functionality
 *
 * OpenAPI spec version: 1.0.0
 * Contact: oleg@processmaker.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProcessMakerApi);
  }
}(this, function(expect, ProcessMakerApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProcessMakerApi.UserAttributes();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserAttributes', function() {
    it('should create an instance of UserAttributes', function() {
      // uncomment below and update the code to test UserAttributes
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be.a(ProcessMakerApi.UserAttributes);
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

    it('should have the property firstname (base name: "firstname")', function() {
      // uncomment below and update the code to test the property firstname
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

    it('should have the property lastname (base name: "lastname")', function() {
      // uncomment below and update the code to test the property lastname
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

    it('should have the property expireDate (base name: "expire_date")', function() {
      // uncomment below and update the code to test the property expireDate
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

    it('should have the property location (base name: "location")', function() {
      // uncomment below and update the code to test the property location
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

    it('should have the property fax (base name: "fax")', function() {
      // uncomment below and update the code to test the property fax
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

    it('should have the property cellular (base name: "cellular")', function() {
      // uncomment below and update the code to test the property cellular
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

    it('should have the property zipCode (base name: "zip_code")', function() {
      // uncomment below and update the code to test the property zipCode
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

    it('should have the property position (base name: "position")', function() {
      // uncomment below and update the code to test the property position
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

    it('should have the property resume (base name: "resume")', function() {
      // uncomment below and update the code to test the property resume
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

    it('should have the property birthday (base name: "birthday")', function() {
      // uncomment below and update the code to test the property birthday
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

    it('should have the property bookmarkStartCases (base name: "bookmark_start_cases")', function() {
      // uncomment below and update the code to test the property bookmarkStartCases
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

    it('should have the property timeZone (base name: "time_zone")', function() {
      // uncomment below and update the code to test the property timeZone
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

    it('should have the property defaultLang (base name: "default_lang")', function() {
      // uncomment below and update the code to test the property defaultLang
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instane = new ProcessMakerApi.UserAttributes();
      //expect(instance).to.be();
    });

  });

}));
